### ISSUE TITLE
Code for the book?

### ISSUE THREAD

**Issue by milanhej** [paTait/dswj#1]
I purchased _Data Science with Julia_, which looks quite useful for my purposes.  On page xvi of the Preface it states that "all of the code for the book is available on Github", and references this URL, but the site still seems empty. Is there somewhere else I should look?  Or will the code indeed be here soon?  Thanks.

**Comment by taglia** [comment]
Same issue here. I would appreciate if you could push the code soon.

**Comment by paTait** [comment]
Hi Everyone,
thanks for the interest in the book.
I have pushed the code to the repo. 
If there are problems/improvements - post them as issues.
Cheers
